### ISSUE TITLE
Support for vscode insider (?)

### ISSUE THREAD

**Issue by sandriaas** [syfxlin/vscode-acrylic#1]
Hi, firstly, thank you so much for your work on this extension. I really love it.
Is it possible to make it work on vscode insider version?

**Comment by bleachedsleet** [comment]
I can also confirm that this extension isn't working on the current Insider version (1.37.0-insider).

**Comment by syfxlin** [comment]
![image](https://user-images.githubusercontent.com/28844480/62264326-083c5380-b452-11e9-8e82-53bbad519ca7.png)
VSCode Insider is unable to access the main thread due to some problems, so the window handle cannot be obtained, so this plugin is temporarily unable to support VSCode Insider. But as long as you can get the window handle, you can make it work.

> VSCode Insider由于一些问题导致无法远程访问主线程，因此无法获取窗口句柄，因此该插件暂时无法支持VSCode Insider。但只要能得到窗口句柄，你就可以使它工作。

**Comment by syfxlin** [comment]
@andrizmitnick @scratchfive 
![image](https://user-images.githubusercontent.com/28844480/62374627-f56b7100-b56e-11e9-9531-f37eaa8246b7.png)
By inserting the code into the main thread, it is now possible to run on VSCode Insider, and I will add support for VSCode Insider in the next release.

> 通过将代码插入主线程的方式，目前已经可以在VSCode Insider上运行，我将在下一个版本增加对VSCode Insider的支持

**Comment by syfxlin** [comment]
This problem has been fixed. It has been released in 1.0.3.
